# Generated by Django 4.1.1 on 2022-11-25 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminPHIS', '0005_phisuser_following_data_alter_menu_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['menucreated']},
        ),
        migrations.AlterModelOptions(
            name='microservice',
            options={'ordering': ['microserviceCreated']},
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='menu',
            name='menustatus',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='submenustatus',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolename', models.CharField(max_length=200)),
                ('roleshortname', models.CharField(max_length=200)),
                ('comment', models.TextField(max_length=400)),
                ('rolestatus', models.CharField(max_length=200)),
                ('roledescription', models.CharField(max_length=400)),
                ('roleupdated', models.DateTimeField(auto_now=True)),
                ('rolecreated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rolecreated'],
            },
        ),
        migrations.AddField(
            model_name='submenu',
            name='role',
            field=models.ManyToManyField(to='adminPHIS.role'),
        ),
    ]